#!/bin/bash

SESSION_NAME="clipygame"
PROJECT_DIR="$HOME/Projects/learning/clipygame/"
PROJECT_VENV="$PROJECT_DIR/.venv"

cd "$PROJECT_DIR" || exit 1

if tmux has-session -t "$SESSION_NAME" 2>/dev/null; then
  echo "Session '$SESSION_NAME' already exists. Attaching..."
  tmux attach -t "$SESSION_NAME/.venv/"
  exit 0
fi

tmux new-session -d -s "$SESSION_NAME" -n "editor" "nvim ."
tmux new-window -t "$SESSION_NAME" -n "git" "lazygit"
tmux new-window -t "$SESSION_NAME" -n "shell"
tmux send-keys -t "$SESSION_NAME:shell" "source $PROJECT_VENV/bin/activate; clear" C-m

tmux select-window -t "$SESSION_NAME:editor"
tmux attach -t "$SESSION_NAME"
